apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: {{ .Values.httpd.replicas }}
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: {{ .Values.httpd.image }}
        ports:
        - containerPort: {{ .Values.httpd.port }}
